//! This crate contains the auto-generated mapping from an icon name
//! (such as `Icon::NetworkWifi`) to the character codepoint `\u{e1ba}`)
//! in Googles Material Icon Font ([https://material.io/tools/icons/](https://material.io/tools/icons/)) -
//! useful if you want to use the material-icons font in user interfaces created
//! in Rust
//!
//! ## Example
//!
//! ```rust
//! use material_icons::{Icon, icon_to_char};
//! let icon_char = icon_to_char(Icon::Rotation3d);
//! assert_eq!('\u{e84d}', icon_char);
//! ```
//!
//! When the resulting character is displayed using any font renderer,
//! the character will result in the "3d_rotation" glyph.
//!
//! ## License (please read - regarding embedded font)
//!
//! According to [https://github.com/google/material-design-icons/blob/master/LICENSE](https://github.com/google/material-design-icons/blob/master/LICENSE)
//! (retrieved 23-10-2018) the font data embedded in this library is licensed under
//! the Apache 2.0 license, which explains the license for this crate.
//!
//! You do not need to attribute Google (although they appreciate it):
//!
//! > "We have made these icons available for you to incorporate into your products
//! > under the Apache License Version 2.0. Feel free to remix and re-share these
//! > icons and documentation in your products. We'd love attribution in your app's
//! > about screen, but it's not required. The only thing we ask is that you not
//! > re-sell these icons."
//!

#[macro_use]
extern crate enum_iterator;

/// Icon containing all possible icon names as enum discriminants
#[repr(C)]
#[derive(Debug, Copy, Clone, IntoEnumIterator, PartialEq, Eq, Hash, PartialOrd, Ord)]
pub enum Icon {
    Rotation3d,
    AcUnit,
    AccessAlarm,
    AccessAlarms,
    AccessTime,
    Accessibility,
    Accessible,
    AccountBalance,
    AccountBalanceWallet,
    AccountBox,
    AccountCircle,
    Adb,
    Add,
    AddAPhoto,
    AddAlarm,
    AddAlert,
    AddBox,
    AddCircle,
    AddCircleOutline,
    AddLocation,
    AddShoppingCart,
    AddToPhotos,
    AddToQueue,
    Adjust,
    AirlineSeatFlat,
    AirlineSeatFlatAngled,
    AirlineSeatIndividualSuite,
    AirlineSeatLegroomExtra,
    AirlineSeatLegroomNormal,
    AirlineSeatLegroomReduced,
    AirlineSeatReclineExtra,
    AirlineSeatReclineNormal,
    AirplanemodeActive,
    AirplanemodeInactive,
    Airplay,
    AirportShuttle,
    Alarm,
    AlarmAdd,
    AlarmOff,
    AlarmOn,
    Album,
    AllInclusive,
    AllOut,
    Android,
    Announcement,
    Apps,
    Archive,
    ArrowBack,
    ArrowDownward,
    ArrowDropDown,
    ArrowDropDownCircle,
    ArrowDropUp,
    ArrowForward,
    ArrowUpward,
    ArtTrack,
    AspectRatio,
    Assessment,
    Assignment,
    AssignmentInd,
    AssignmentLate,
    AssignmentReturn,
    AssignmentReturned,
    AssignmentTurnedIn,
    Assistant,
    AssistantPhoto,
    AttachFile,
    AttachMoney,
    Attachment,
    Audiotrack,
    Autorenew,
    AvTimer,
    Backspace,
    Backup,
    BatteryAlert,
    BatteryChargingFull,
    BatteryFull,
    BatteryStd,
    BatteryUnknown,
    BeachAccess,
    Beenhere,
    Block,
    Bluetooth,
    BluetoothAudio,
    BluetoothConnected,
    BluetoothDisabled,
    BluetoothSearching,
    BlurCircular,
    BlurLinear,
    BlurOff,
    BlurOn,
    Book,
    Bookmark,
    BookmarkBorder,
    BorderAll,
    BorderBottom,
    BorderClear,
    BorderColor,
    BorderHorizontal,
    BorderInner,
    BorderLeft,
    BorderOuter,
    BorderRight,
    BorderStyle,
    BorderTop,
    BorderVertical,
    BrandingWatermark,
    Brightness1,
    Brightness2,
    Brightness3,
    Brightness4,
    Brightness5,
    Brightness6,
    Brightness7,
    BrightnessAuto,
    BrightnessHigh,
    BrightnessLow,
    BrightnessMedium,
    BrokenImage,
    Brush,
    BubbleChart,
    BugReport,
    Build,
    BurstMode,
    Business,
    BusinessCenter,
    Cached,
    Cake,
    Call,
    CallEnd,
    CallMade,
    CallMerge,
    CallMissed,
    CallMissedOutgoing,
    CallReceived,
    CallSplit,
    CallToAction,
    Camera,
    CameraAlt,
    CameraEnhance,
    CameraFront,
    CameraRear,
    CameraRoll,
    Cancel,
    CardGiftcard,
    CardMembership,
    CardTravel,
    Casino,
    Cast,
    CastConnected,
    CenterFocusStrong,
    CenterFocusWeak,
    ChangeHistory,
    Chat,
    ChatBubble,
    ChatBubbleOutline,
    Check,
    CheckBox,
    CheckBoxOutlineBlank,
    CheckCircle,
    ChevronLeft,
    ChevronRight,
    ChildCare,
    ChildFriendly,
    ChromeReaderMode,
    Class,
    Clear,
    ClearAll,
    Close,
    ClosedCaption,
    Cloud,
    CloudCircle,
    CloudDone,
    CloudDownload,
    CloudOff,
    CloudQueue,
    CloudUpload,
    Code,
    Collections,
    CollectionsBookmark,
    ColorLens,
    Colorize,
    Comment,
    Compare,
    CompareArrows,
    Computer,
    ConfirmationNumber,
    ContactMail,
    ContactPhone,
    Contacts,
    ContentCopy,
    ContentCut,
    ContentPaste,
    ControlPoint,
    ControlPointDuplicate,
    Copyright,
    Create,
    CreateNewFolder,
    CreditCard,
    Crop,
    Crop169,
    Crop32,
    Crop54,
    Crop75,
    CropDin,
    CropFree,
    CropLandscape,
    CropOriginal,
    CropPortrait,
    CropRotate,
    CropSquare,
    Dashboard,
    DataUsage,
    DateRange,
    Dehaze,
    Delete,
    DeleteForever,
    DeleteSweep,
    Description,
    DesktopMac,
    DesktopWindows,
    Details,
    DeveloperBoard,
    DeveloperMode,
    DeviceHub,
    Devices,
    DevicesOther,
    DialerSip,
    Dialpad,
    Directions,
    DirectionsBike,
    DirectionsBoat,
    DirectionsBus,
    DirectionsCar,
    DirectionsRailway,
    DirectionsRun,
    DirectionsSubway,
    DirectionsTransit,
    DirectionsWalk,
    DiscFull,
    Dns,
    DoNotDisturb,
    DoNotDisturbAlt,
    DoNotDisturbOff,
    DoNotDisturbOn,
    Dock,
    Domain,
    Done,
    DoneAll,
    DonutLarge,
    DonutSmall,
    Drafts,
    DragHandle,
    DriveEta,
    Dvr,
    Edit,
    EditLocation,
    Eject,
    Email,
    EnhancedEncryption,
    Equalizer,
    Error,
    ErrorOutline,
    EuroSymbol,
    EvStation,
    Event,
    EventAvailable,
    EventBusy,
    EventNote,
    EventSeat,
    ExitToApp,
    ExpandLess,
    ExpandMore,
    Explicit,
    Explore,
    Exposure,
    ExposureNeg1,
    ExposureNeg2,
    ExposurePlus1,
    ExposurePlus2,
    ExposureZero,
    Extension,
    Face,
    FastForward,
    FastRewind,
    Favorite,
    FavoriteBorder,
    FeaturedPlayList,
    FeaturedVideo,
    Feedback,
    FiberDvr,
    FiberManualRecord,
    FiberNew,
    FiberPin,
    FiberSmartRecord,
    FileDownload,
    FileUpload,
    Filter,
    Filter1,
    Filter2,
    Filter3,
    Filter4,
    Filter5,
    Filter6,
    Filter7,
    Filter8,
    Filter9,
    Filter9Plus,
    FilterBAndW,
    FilterCenterFocus,
    FilterDrama,
    FilterFrames,
    FilterHdr,
    FilterList,
    FilterNone,
    FilterTiltShift,
    FilterVintage,
    FindInPage,
    FindReplace,
    Fingerprint,
    FirstPage,
    FitnessCenter,
    Flag,
    Flare,
    FlashAuto,
    FlashOff,
    FlashOn,
    Flight,
    FlightLand,
    FlightTakeoff,
    Flip,
    FlipToBack,
    FlipToFront,
    Folder,
    FolderOpen,
    FolderShared,
    FolderSpecial,
    FontDownload,
    FormatAlignCenter,
    FormatAlignJustify,
    FormatAlignLeft,
    FormatAlignRight,
    FormatBold,
    FormatClear,
    FormatColorFill,
    FormatColorReset,
    FormatColorText,
    FormatIndentDecrease,
    FormatIndentIncrease,
    FormatItalic,
    FormatLineSpacing,
    FormatListBulleted,
    FormatListNumbered,
    FormatPaint,
    FormatQuote,
    FormatShapes,
    FormatSize,
    FormatStrikethrough,
    FormatTextdirectionLToR,
    FormatTextdirectionRToL,
    FormatUnderlined,
    Forum,
    Forward,
    Forward10,
    Forward30,
    Forward5,
    FreeBreakfast,
    Fullscreen,
    FullscreenExit,
    Functions,
    GTranslate,
    Gamepad,
    Games,
    Gavel,
    Gesture,
    GetApp,
    Gif,
    GolfCourse,
    GpsFixed,
    GpsNotFixed,
    GpsOff,
    Grade,
    Gradient,
    Grain,
    GraphicEq,
    GridOff,
    GridOn,
    Group,
    GroupAdd,
    GroupWork,
    Hd,
    HdrOff,
    HdrOn,
    HdrStrong,
    HdrWeak,
    Headset,
    HeadsetMic,
    Healing,
    Hearing,
    Help,
    HelpOutline,
    HighQuality,
    Highlight,
    HighlightOff,
    History,
    Home,
    HotTub,
    Hotel,
    HourglassEmpty,
    HourglassFull,
    Http,
    Https,
    Image,
    ImageAspectRatio,
    ImportContacts,
    ImportExport,
    ImportantDevices,
    Inbox,
    IndeterminateCheckBox,
    Info,
    InfoOutline,
    Input,
    InsertChart,
    InsertComment,
    InsertDriveFile,
    InsertEmoticon,
    InsertInvitation,
    InsertLink,
    InsertPhoto,
    InvertColors,
    InvertColorsOff,
    Iso,
    Keyboard,
    KeyboardArrowDown,
    KeyboardArrowLeft,
    KeyboardArrowRight,
    KeyboardArrowUp,
    KeyboardBackspace,
    KeyboardCapslock,
    KeyboardHide,
    KeyboardReturn,
    KeyboardTab,
    KeyboardVoice,
    Kitchen,
    Label,
    LabelOutline,
    Landscape,
    Language,
    Laptop,
    LaptopChromebook,
    LaptopMac,
    LaptopWindows,
    LastPage,
    Launch,
    Layers,
    LayersClear,
    LeakAdd,
    LeakRemove,
    Lens,
    LibraryAdd,
    LibraryBooks,
    LibraryMusic,
    LightbulbOutline,
    LineStyle,
    LineWeight,
    LinearScale,
    Link,
    LinkedCamera,
    List,
    LiveHelp,
    LiveTv,
    LocalActivity,
    LocalAirport,
    LocalAtm,
    LocalBar,
    LocalCafe,
    LocalCarWash,
    LocalConvenienceStore,
    LocalDining,
    LocalDrink,
    LocalFlorist,
    LocalGasStation,
    LocalGroceryStore,
    LocalHospital,
    LocalHotel,
    LocalLaundryService,
    LocalLibrary,
    LocalMall,
    LocalMovies,
    LocalOffer,
    LocalParking,
    LocalPharmacy,
    LocalPhone,
    LocalPizza,
    LocalPlay,
    LocalPostOffice,
    LocalPrintshop,
    LocalSee,
    LocalShipping,
    LocalTaxi,
    LocationCity,
    LocationDisabled,
    LocationOff,
    LocationOn,
    LocationSearching,
    Lock,
    LockOpen,
    LockOutline,
    Looks,
    Looks3,
    Looks4,
    Looks5,
    Looks6,
    LooksOne,
    LooksTwo,
    Loop,
    Loupe,
    LowPriority,
    Loyalty,
    Mail,
    MailOutline,
    Map,
    Markunread,
    MarkunreadMailbox,
    Memory,
    Menu,
    MergeType,
    Message,
    Mic,
    MicNone,
    MicOff,
    Mms,
    ModeComment,
    ModeEdit,
    MonetizationOn,
    MoneyOff,
    MonochromePhotos,
    Mood,
    MoodBad,
    More,
    MoreHoriz,
    MoreVert,
    Motorcycle,
    Mouse,
    MoveToInbox,
    Movie,
    MovieCreation,
    MovieFilter,
    MultilineChart,
    MusicNote,
    MusicVideo,
    MyLocation,
    Nature,
    NaturePeople,
    NavigateBefore,
    NavigateNext,
    Navigation,
    NearMe,
    NetworkCell,
    NetworkCheck,
    NetworkLocked,
    NetworkWifi,
    NewReleases,
    NextWeek,
    Nfc,
    NoEncryption,
    NoSim,
    NotInterested,
    Note,
    NoteAdd,
    Notifications,
    NotificationsActive,
    NotificationsNone,
    NotificationsOff,
    NotificationsPaused,
    OfflinePin,
    OndemandVideo,
    Opacity,
    OpenInBrowser,
    OpenInNew,
    OpenWith,
    Pages,
    Pageview,
    Palette,
    PanTool,
    Panorama,
    PanoramaFishEye,
    PanoramaHorizontal,
    PanoramaVertical,
    PanoramaWideAngle,
    PartyMode,
    Pause,
    PauseCircleFilled,
    PauseCircleOutline,
    Payment,
    People,
    PeopleOutline,
    PermCameraMic,
    PermContactCalendar,
    PermDataSetting,
    PermDeviceInformation,
    PermIdentity,
    PermMedia,
    PermPhoneMsg,
    PermScanWifi,
    Person,
    PersonAdd,
    PersonOutline,
    PersonPin,
    PersonPinCircle,
    PersonalVideo,
    Pets,
    Phone,
    PhoneAndroid,
    PhoneBluetoothSpeaker,
    PhoneForwarded,
    PhoneInTalk,
    PhoneIphone,
    PhoneLocked,
    PhoneMissed,
    PhonePaused,
    Phonelink,
    PhonelinkErase,
    PhonelinkLock,
    PhonelinkOff,
    PhonelinkRing,
    PhonelinkSetup,
    Photo,
    PhotoAlbum,
    PhotoCamera,
    PhotoFilter,
    PhotoLibrary,
    PhotoSizeSelectActual,
    PhotoSizeSelectLarge,
    PhotoSizeSelectSmall,
    PictureAsPdf,
    PictureInPicture,
    PictureInPictureAlt,
    PieChart,
    PieChartOutlined,
    PinDrop,
    Place,
    PlayArrow,
    PlayCircleFilled,
    PlayCircleOutline,
    PlayForWork,
    PlaylistAdd,
    PlaylistAddCheck,
    PlaylistPlay,
    PlusOne,
    Poll,
    Polymer,
    Pool,
    PortableWifiOff,
    Portrait,
    Power,
    PowerInput,
    PowerSettingsNew,
    PregnantWoman,
    PresentToAll,
    Print,
    PriorityHigh,
    Public,
    Publish,
    QueryBuilder,
    QuestionAnswer,
    Queue,
    QueueMusic,
    QueuePlayNext,
    Radio,
    RadioButtonChecked,
    RadioButtonUnchecked,
    RateReview,
    Receipt,
    RecentActors,
    RecordVoiceOver,
    Redeem,
    Redo,
    Refresh,
    Remove,
    RemoveCircle,
    RemoveCircleOutline,
    RemoveFromQueue,
    RemoveRedEye,
    RemoveShoppingCart,
    Reorder,
    Repeat,
    RepeatOne,
    Replay,
    Replay10,
    Replay30,
    Replay5,
    Reply,
    ReplyAll,
    Report,
    ReportProblem,
    Restaurant,
    RestaurantMenu,
    Restore,
    RestorePage,
    RingVolume,
    Room,
    RoomService,
    Rotate90DegreesCcw,
    RotateLeft,
    RotateRight,
    RoundedCorner,
    Router,
    Rowing,
    RssFeed,
    RvHookup,
    Satellite,
    Save,
    Scanner,
    Schedule,
    School,
    ScreenLockLandscape,
    ScreenLockPortrait,
    ScreenLockRotation,
    ScreenRotation,
    ScreenShare,
    SdCard,
    SdStorage,
    Search,
    Security,
    SelectAll,
    Send,
    SentimentDissatisfied,
    SentimentNeutral,
    SentimentSatisfied,
    SentimentVeryDissatisfied,
    SentimentVerySatisfied,
    Settings,
    SettingsApplications,
    SettingsBackupRestore,
    SettingsBluetooth,
    SettingsBrightness,
    SettingsCell,
    SettingsEthernet,
    SettingsInputAntenna,
    SettingsInputComponent,
    SettingsInputComposite,
    SettingsInputHdmi,
    SettingsInputSvideo,
    SettingsOverscan,
    SettingsPhone,
    SettingsPower,
    SettingsRemote,
    SettingsSystemDaydream,
    SettingsVoice,
    Share,
    Shop,
    ShopTwo,
    ShoppingBasket,
    ShoppingCart,
    ShortText,
    ShowChart,
    Shuffle,
    SignalCellular4Bar,
    SignalCellularConnectedNoInternet4Bar,
    SignalCellularNoSim,
    SignalCellularNull,
    SignalCellularOff,
    SignalWifi4Bar,
    SignalWifi4BarLock,
    SignalWifiOff,
    SimCard,
    SimCardAlert,
    SkipNext,
    SkipPrevious,
    Slideshow,
    SlowMotionVideo,
    Smartphone,
    SmokeFree,
    SmokingRooms,
    Sms,
    SmsFailed,
    Snooze,
    Sort,
    SortByAlpha,
    Spa,
    SpaceBar,
    Speaker,
    SpeakerGroup,
    SpeakerNotes,
    SpeakerNotesOff,
    SpeakerPhone,
    Spellcheck,
    Star,
    StarBorder,
    StarHalf,
    Stars,
    StayCurrentLandscape,
    StayCurrentPortrait,
    StayPrimaryLandscape,
    StayPrimaryPortrait,
    Stop,
    StopScreenShare,
    Storage,
    Store,
    StoreMallDirectory,
    Straighten,
    Streetview,
    StrikethroughS,
    Style,
    SubdirectoryArrowLeft,
    SubdirectoryArrowRight,
    Subject,
    Subscriptions,
    Subtitles,
    Subway,
    SupervisorAccount,
    SurroundSound,
    SwapCalls,
    SwapHoriz,
    SwapVert,
    SwapVerticalCircle,
    SwitchCamera,
    SwitchVideo,
    Sync,
    SyncDisabled,
    SyncProblem,
    SystemUpdate,
    SystemUpdateAlt,
    Tab,
    TabUnselected,
    Tablet,
    TabletAndroid,
    TabletMac,
    TagFaces,
    TapAndPlay,
    Terrain,
    TextFields,
    TextFormat,
    Textsms,
    Texture,
    Theaters,
    ThumbDown,
    ThumbUp,
    ThumbsUpDown,
    TimeToLeave,
    Timelapse,
    Timeline,
    Timer,
    Timer10,
    Timer3,
    TimerOff,
    Title,
    Toc,
    Today,
    Toll,
    Tonality,
    TouchApp,
    Toys,
    TrackChanges,
    Traffic,
    Train,
    Tram,
    TransferWithinAStation,
    Transform,
    Translate,
    TrendingDown,
    TrendingFlat,
    TrendingUp,
    Tune,
    TurnedIn,
    TurnedInNot,
    Tv,
    Unarchive,
    Undo,
    UnfoldLess,
    UnfoldMore,
    Update,
    Usb,
    VerifiedUser,
    VerticalAlignBottom,
    VerticalAlignCenter,
    VerticalAlignTop,
    Vibration,
    VideoCall,
    VideoLabel,
    VideoLibrary,
    Videocam,
    VideocamOff,
    VideogameAsset,
    ViewAgenda,
    ViewArray,
    ViewCarousel,
    ViewColumn,
    ViewComfy,
    ViewCompact,
    ViewDay,
    ViewHeadline,
    ViewList,
    ViewModule,
    ViewQuilt,
    ViewStream,
    ViewWeek,
    Vignette,
    Visibility,
    VisibilityOff,
    VoiceChat,
    Voicemail,
    VolumeDown,
    VolumeMute,
    VolumeOff,
    VolumeUp,
    VpnKey,
    VpnLock,
    Wallpaper,
    Warning,
    Watch,
    WatchLater,
    WbAuto,
    WbCloudy,
    WbIncandescent,
    WbIridescent,
    WbSunny,
    Wc,
    Web,
    WebAsset,
    Weekend,
    Whatshot,
    Widgets,
    Wifi,
    WifiLock,
    WifiTethering,
    Work,
    WrapText,
    YoutubeSearchedFor,
    ZoomIn,
    ZoomOut,
    ZoomOutMap,
}


/// Converts an `Icon` to a `char`. Same as `format!("{}", icon)` or `icon.to_char()`.
#[no_mangle]
pub fn icon_to_char(icon: Icon) -> char {
    use self::Icon::*;
    match icon {
        Rotation3d => '\u{e84d}',
        AcUnit => '\u{eb3b}',
        AccessAlarm => '\u{e190}',
        AccessAlarms => '\u{e191}',
        AccessTime => '\u{e192}',
        Accessibility => '\u{e84e}',
        Accessible => '\u{e914}',
        AccountBalance => '\u{e84f}',
        AccountBalanceWallet => '\u{e850}',
        AccountBox => '\u{e851}',
        AccountCircle => '\u{e853}',
        Adb => '\u{e60e}',
        Add => '\u{e145}',
        AddAPhoto => '\u{e439}',
        AddAlarm => '\u{e193}',
        AddAlert => '\u{e003}',
        AddBox => '\u{e146}',
        AddCircle => '\u{e147}',
        AddCircleOutline => '\u{e148}',
        AddLocation => '\u{e567}',
        AddShoppingCart => '\u{e854}',
        AddToPhotos => '\u{e39d}',
        AddToQueue => '\u{e05c}',
        Adjust => '\u{e39e}',
        AirlineSeatFlat => '\u{e630}',
        AirlineSeatFlatAngled => '\u{e631}',
        AirlineSeatIndividualSuite => '\u{e632}',
        AirlineSeatLegroomExtra => '\u{e633}',
        AirlineSeatLegroomNormal => '\u{e634}',
        AirlineSeatLegroomReduced => '\u{e635}',
        AirlineSeatReclineExtra => '\u{e636}',
        AirlineSeatReclineNormal => '\u{e637}',
        AirplanemodeActive => '\u{e195}',
        AirplanemodeInactive => '\u{e194}',
        Airplay => '\u{e055}',
        AirportShuttle => '\u{eb3c}',
        Alarm => '\u{e855}',
        AlarmAdd => '\u{e856}',
        AlarmOff => '\u{e857}',
        AlarmOn => '\u{e858}',
        Album => '\u{e019}',
        AllInclusive => '\u{eb3d}',
        AllOut => '\u{e90b}',
        Android => '\u{e859}',
        Announcement => '\u{e85a}',
        Apps => '\u{e5c3}',
        Archive => '\u{e149}',
        ArrowBack => '\u{e5c4}',
        ArrowDownward => '\u{e5db}',
        ArrowDropDown => '\u{e5c5}',
        ArrowDropDownCircle => '\u{e5c6}',
        ArrowDropUp => '\u{e5c7}',
        ArrowForward => '\u{e5c8}',
        ArrowUpward => '\u{e5d8}',
        ArtTrack => '\u{e060}',
        AspectRatio => '\u{e85b}',
        Assessment => '\u{e85c}',
        Assignment => '\u{e85d}',
        AssignmentInd => '\u{e85e}',
        AssignmentLate => '\u{e85f}',
        AssignmentReturn => '\u{e860}',
        AssignmentReturned => '\u{e861}',
        AssignmentTurnedIn => '\u{e862}',
        Assistant => '\u{e39f}',
        AssistantPhoto => '\u{e3a0}',
        AttachFile => '\u{e226}',
        AttachMoney => '\u{e227}',
        Attachment => '\u{e2bc}',
        Audiotrack => '\u{e3a1}',
        Autorenew => '\u{e863}',
        AvTimer => '\u{e01b}',
        Backspace => '\u{e14a}',
        Backup => '\u{e864}',
        BatteryAlert => '\u{e19c}',
        BatteryChargingFull => '\u{e1a3}',
        BatteryFull => '\u{e1a4}',
        BatteryStd => '\u{e1a5}',
        BatteryUnknown => '\u{e1a6}',
        BeachAccess => '\u{eb3e}',
        Beenhere => '\u{e52d}',
        Block => '\u{e14b}',
        Bluetooth => '\u{e1a7}',
        BluetoothAudio => '\u{e60f}',
        BluetoothConnected => '\u{e1a8}',
        BluetoothDisabled => '\u{e1a9}',
        BluetoothSearching => '\u{e1aa}',
        BlurCircular => '\u{e3a2}',
        BlurLinear => '\u{e3a3}',
        BlurOff => '\u{e3a4}',
        BlurOn => '\u{e3a5}',
        Book => '\u{e865}',
        Bookmark => '\u{e866}',
        BookmarkBorder => '\u{e867}',
        BorderAll => '\u{e228}',
        BorderBottom => '\u{e229}',
        BorderClear => '\u{e22a}',
        BorderColor => '\u{e22b}',
        BorderHorizontal => '\u{e22c}',
        BorderInner => '\u{e22d}',
        BorderLeft => '\u{e22e}',
        BorderOuter => '\u{e22f}',
        BorderRight => '\u{e230}',
        BorderStyle => '\u{e231}',
        BorderTop => '\u{e232}',
        BorderVertical => '\u{e233}',
        BrandingWatermark => '\u{e06b}',
        Brightness1 => '\u{e3a6}',
        Brightness2 => '\u{e3a7}',
        Brightness3 => '\u{e3a8}',
        Brightness4 => '\u{e3a9}',
        Brightness5 => '\u{e3aa}',
        Brightness6 => '\u{e3ab}',
        Brightness7 => '\u{e3ac}',
        BrightnessAuto => '\u{e1ab}',
        BrightnessHigh => '\u{e1ac}',
        BrightnessLow => '\u{e1ad}',
        BrightnessMedium => '\u{e1ae}',
        BrokenImage => '\u{e3ad}',
        Brush => '\u{e3ae}',
        BubbleChart => '\u{e6dd}',
        BugReport => '\u{e868}',
        Build => '\u{e869}',
        BurstMode => '\u{e43c}',
        Business => '\u{e0af}',
        BusinessCenter => '\u{eb3f}',
        Cached => '\u{e86a}',
        Cake => '\u{e7e9}',
        Call => '\u{e0b0}',
        CallEnd => '\u{e0b1}',
        CallMade => '\u{e0b2}',
        CallMerge => '\u{e0b3}',
        CallMissed => '\u{e0b4}',
        CallMissedOutgoing => '\u{e0e4}',
        CallReceived => '\u{e0b5}',
        CallSplit => '\u{e0b6}',
        CallToAction => '\u{e06c}',
        Camera => '\u{e3af}',
        CameraAlt => '\u{e3b0}',
        CameraEnhance => '\u{e8fc}',
        CameraFront => '\u{e3b1}',
        CameraRear => '\u{e3b2}',
        CameraRoll => '\u{e3b3}',
        Cancel => '\u{e5c9}',
        CardGiftcard => '\u{e8f6}',
        CardMembership => '\u{e8f7}',
        CardTravel => '\u{e8f8}',
        Casino => '\u{eb40}',
        Cast => '\u{e307}',
        CastConnected => '\u{e308}',
        CenterFocusStrong => '\u{e3b4}',
        CenterFocusWeak => '\u{e3b5}',
        ChangeHistory => '\u{e86b}',
        Chat => '\u{e0b7}',
        ChatBubble => '\u{e0ca}',
        ChatBubbleOutline => '\u{e0cb}',
        Check => '\u{e5ca}',
        CheckBox => '\u{e834}',
        CheckBoxOutlineBlank => '\u{e835}',
        CheckCircle => '\u{e86c}',
        ChevronLeft => '\u{e5cb}',
        ChevronRight => '\u{e5cc}',
        ChildCare => '\u{eb41}',
        ChildFriendly => '\u{eb42}',
        ChromeReaderMode => '\u{e86d}',
        Class => '\u{e86e}',
        Clear => '\u{e14c}',
        ClearAll => '\u{e0b8}',
        Close => '\u{e5cd}',
        ClosedCaption => '\u{e01c}',
        Cloud => '\u{e2bd}',
        CloudCircle => '\u{e2be}',
        CloudDone => '\u{e2bf}',
        CloudDownload => '\u{e2c0}',
        CloudOff => '\u{e2c1}',
        CloudQueue => '\u{e2c2}',
        CloudUpload => '\u{e2c3}',
        Code => '\u{e86f}',
        Collections => '\u{e3b6}',
        CollectionsBookmark => '\u{e431}',
        ColorLens => '\u{e3b7}',
        Colorize => '\u{e3b8}',
        Comment => '\u{e0b9}',
        Compare => '\u{e3b9}',
        CompareArrows => '\u{e915}',
        Computer => '\u{e30a}',
        ConfirmationNumber => '\u{e638}',
        ContactMail => '\u{e0d0}',
        ContactPhone => '\u{e0cf}',
        Contacts => '\u{e0ba}',
        ContentCopy => '\u{e14d}',
        ContentCut => '\u{e14e}',
        ContentPaste => '\u{e14f}',
        ControlPoint => '\u{e3ba}',
        ControlPointDuplicate => '\u{e3bb}',
        Copyright => '\u{e90c}',
        Create => '\u{e150}',
        CreateNewFolder => '\u{e2cc}',
        CreditCard => '\u{e870}',
        Crop => '\u{e3be}',
        Crop169 => '\u{e3bc}',
        Crop32 => '\u{e3bd}',
        Crop54 => '\u{e3bf}',
        Crop75 => '\u{e3c0}',
        CropDin => '\u{e3c1}',
        CropFree => '\u{e3c2}',
        CropLandscape => '\u{e3c3}',
        CropOriginal => '\u{e3c4}',
        CropPortrait => '\u{e3c5}',
        CropRotate => '\u{e437}',
        CropSquare => '\u{e3c6}',
        Dashboard => '\u{e871}',
        DataUsage => '\u{e1af}',
        DateRange => '\u{e916}',
        Dehaze => '\u{e3c7}',
        Delete => '\u{e872}',
        DeleteForever => '\u{e92b}',
        DeleteSweep => '\u{e16c}',
        Description => '\u{e873}',
        DesktopMac => '\u{e30b}',
        DesktopWindows => '\u{e30c}',
        Details => '\u{e3c8}',
        DeveloperBoard => '\u{e30d}',
        DeveloperMode => '\u{e1b0}',
        DeviceHub => '\u{e335}',
        Devices => '\u{e1b1}',
        DevicesOther => '\u{e337}',
        DialerSip => '\u{e0bb}',
        Dialpad => '\u{e0bc}',
        Directions => '\u{e52e}',
        DirectionsBike => '\u{e52f}',
        DirectionsBoat => '\u{e532}',
        DirectionsBus => '\u{e530}',
        DirectionsCar => '\u{e531}',
        DirectionsRailway => '\u{e534}',
        DirectionsRun => '\u{e566}',
        DirectionsSubway => '\u{e533}',
        DirectionsTransit => '\u{e535}',
        DirectionsWalk => '\u{e536}',
        DiscFull => '\u{e610}',
        Dns => '\u{e875}',
        DoNotDisturb => '\u{e612}',
        DoNotDisturbAlt => '\u{e611}',
        DoNotDisturbOff => '\u{e643}',
        DoNotDisturbOn => '\u{e644}',
        Dock => '\u{e30e}',
        Domain => '\u{e7ee}',
        Done => '\u{e876}',
        DoneAll => '\u{e877}',
        DonutLarge => '\u{e917}',
        DonutSmall => '\u{e918}',
        Drafts => '\u{e151}',
        DragHandle => '\u{e25d}',
        DriveEta => '\u{e613}',
        Dvr => '\u{e1b2}',
        Edit => '\u{e3c9}',
        EditLocation => '\u{e568}',
        Eject => '\u{e8fb}',
        Email => '\u{e0be}',
        EnhancedEncryption => '\u{e63f}',
        Equalizer => '\u{e01d}',
        Error => '\u{e000}',
        ErrorOutline => '\u{e001}',
        EuroSymbol => '\u{e926}',
        EvStation => '\u{e56d}',
        Event => '\u{e878}',
        EventAvailable => '\u{e614}',
        EventBusy => '\u{e615}',
        EventNote => '\u{e616}',
        EventSeat => '\u{e903}',
        ExitToApp => '\u{e879}',
        ExpandLess => '\u{e5ce}',
        ExpandMore => '\u{e5cf}',
        Explicit => '\u{e01e}',
        Explore => '\u{e87a}',
        Exposure => '\u{e3ca}',
        ExposureNeg1 => '\u{e3cb}',
        ExposureNeg2 => '\u{e3cc}',
        ExposurePlus1 => '\u{e3cd}',
        ExposurePlus2 => '\u{e3ce}',
        ExposureZero => '\u{e3cf}',
        Extension => '\u{e87b}',
        Face => '\u{e87c}',
        FastForward => '\u{e01f}',
        FastRewind => '\u{e020}',
        Favorite => '\u{e87d}',
        FavoriteBorder => '\u{e87e}',
        FeaturedPlayList => '\u{e06d}',
        FeaturedVideo => '\u{e06e}',
        Feedback => '\u{e87f}',
        FiberDvr => '\u{e05d}',
        FiberManualRecord => '\u{e061}',
        FiberNew => '\u{e05e}',
        FiberPin => '\u{e06a}',
        FiberSmartRecord => '\u{e062}',
        FileDownload => '\u{e2c4}',
        FileUpload => '\u{e2c6}',
        Filter => '\u{e3d3}',
        Filter1 => '\u{e3d0}',
        Filter2 => '\u{e3d1}',
        Filter3 => '\u{e3d2}',
        Filter4 => '\u{e3d4}',
        Filter5 => '\u{e3d5}',
        Filter6 => '\u{e3d6}',
        Filter7 => '\u{e3d7}',
        Filter8 => '\u{e3d8}',
        Filter9 => '\u{e3d9}',
        Filter9Plus => '\u{e3da}',
        FilterBAndW => '\u{e3db}',
        FilterCenterFocus => '\u{e3dc}',
        FilterDrama => '\u{e3dd}',
        FilterFrames => '\u{e3de}',
        FilterHdr => '\u{e3df}',
        FilterList => '\u{e152}',
        FilterNone => '\u{e3e0}',
        FilterTiltShift => '\u{e3e2}',
        FilterVintage => '\u{e3e3}',
        FindInPage => '\u{e880}',
        FindReplace => '\u{e881}',
        Fingerprint => '\u{e90d}',
        FirstPage => '\u{e5dc}',
        FitnessCenter => '\u{eb43}',
        Flag => '\u{e153}',
        Flare => '\u{e3e4}',
        FlashAuto => '\u{e3e5}',
        FlashOff => '\u{e3e6}',
        FlashOn => '\u{e3e7}',
        Flight => '\u{e539}',
        FlightLand => '\u{e904}',
        FlightTakeoff => '\u{e905}',
        Flip => '\u{e3e8}',
        FlipToBack => '\u{e882}',
        FlipToFront => '\u{e883}',
        Folder => '\u{e2c7}',
        FolderOpen => '\u{e2c8}',
        FolderShared => '\u{e2c9}',
        FolderSpecial => '\u{e617}',
        FontDownload => '\u{e167}',
        FormatAlignCenter => '\u{e234}',
        FormatAlignJustify => '\u{e235}',
        FormatAlignLeft => '\u{e236}',
        FormatAlignRight => '\u{e237}',
        FormatBold => '\u{e238}',
        FormatClear => '\u{e239}',
        FormatColorFill => '\u{e23a}',
        FormatColorReset => '\u{e23b}',
        FormatColorText => '\u{e23c}',
        FormatIndentDecrease => '\u{e23d}',
        FormatIndentIncrease => '\u{e23e}',
        FormatItalic => '\u{e23f}',
        FormatLineSpacing => '\u{e240}',
        FormatListBulleted => '\u{e241}',
        FormatListNumbered => '\u{e242}',
        FormatPaint => '\u{e243}',
        FormatQuote => '\u{e244}',
        FormatShapes => '\u{e25e}',
        FormatSize => '\u{e245}',
        FormatStrikethrough => '\u{e246}',
        FormatTextdirectionLToR => '\u{e247}',
        FormatTextdirectionRToL => '\u{e248}',
        FormatUnderlined => '\u{e249}',
        Forum => '\u{e0bf}',
        Forward => '\u{e154}',
        Forward10 => '\u{e056}',
        Forward30 => '\u{e057}',
        Forward5 => '\u{e058}',
        FreeBreakfast => '\u{eb44}',
        Fullscreen => '\u{e5d0}',
        FullscreenExit => '\u{e5d1}',
        Functions => '\u{e24a}',
        GTranslate => '\u{e927}',
        Gamepad => '\u{e30f}',
        Games => '\u{e021}',
        Gavel => '\u{e90e}',
        Gesture => '\u{e155}',
        GetApp => '\u{e884}',
        Gif => '\u{e908}',
        GolfCourse => '\u{eb45}',
        GpsFixed => '\u{e1b3}',
        GpsNotFixed => '\u{e1b4}',
        GpsOff => '\u{e1b5}',
        Grade => '\u{e885}',
        Gradient => '\u{e3e9}',
        Grain => '\u{e3ea}',
        GraphicEq => '\u{e1b8}',
        GridOff => '\u{e3eb}',
        GridOn => '\u{e3ec}',
        Group => '\u{e7ef}',
        GroupAdd => '\u{e7f0}',
        GroupWork => '\u{e886}',
        Hd => '\u{e052}',
        HdrOff => '\u{e3ed}',
        HdrOn => '\u{e3ee}',
        HdrStrong => '\u{e3f1}',
        HdrWeak => '\u{e3f2}',
        Headset => '\u{e310}',
        HeadsetMic => '\u{e311}',
        Healing => '\u{e3f3}',
        Hearing => '\u{e023}',
        Help => '\u{e887}',
        HelpOutline => '\u{e8fd}',
        HighQuality => '\u{e024}',
        Highlight => '\u{e25f}',
        HighlightOff => '\u{e888}',
        History => '\u{e889}',
        Home => '\u{e88a}',
        HotTub => '\u{eb46}',
        Hotel => '\u{e53a}',
        HourglassEmpty => '\u{e88b}',
        HourglassFull => '\u{e88c}',
        Http => '\u{e902}',
        Https => '\u{e88d}',
        Image => '\u{e3f4}',
        ImageAspectRatio => '\u{e3f5}',
        ImportContacts => '\u{e0e0}',
        ImportExport => '\u{e0c3}',
        ImportantDevices => '\u{e912}',
        Inbox => '\u{e156}',
        IndeterminateCheckBox => '\u{e909}',
        Info => '\u{e88e}',
        InfoOutline => '\u{e88f}',
        Input => '\u{e890}',
        InsertChart => '\u{e24b}',
        InsertComment => '\u{e24c}',
        InsertDriveFile => '\u{e24d}',
        InsertEmoticon => '\u{e24e}',
        InsertInvitation => '\u{e24f}',
        InsertLink => '\u{e250}',
        InsertPhoto => '\u{e251}',
        InvertColors => '\u{e891}',
        InvertColorsOff => '\u{e0c4}',
        Iso => '\u{e3f6}',
        Keyboard => '\u{e312}',
        KeyboardArrowDown => '\u{e313}',
        KeyboardArrowLeft => '\u{e314}',
        KeyboardArrowRight => '\u{e315}',
        KeyboardArrowUp => '\u{e316}',
        KeyboardBackspace => '\u{e317}',
        KeyboardCapslock => '\u{e318}',
        KeyboardHide => '\u{e31a}',
        KeyboardReturn => '\u{e31b}',
        KeyboardTab => '\u{e31c}',
        KeyboardVoice => '\u{e31d}',
        Kitchen => '\u{eb47}',
        Label => '\u{e892}',
        LabelOutline => '\u{e893}',
        Landscape => '\u{e3f7}',
        Language => '\u{e894}',
        Laptop => '\u{e31e}',
        LaptopChromebook => '\u{e31f}',
        LaptopMac => '\u{e320}',
        LaptopWindows => '\u{e321}',
        LastPage => '\u{e5dd}',
        Launch => '\u{e895}',
        Layers => '\u{e53b}',
        LayersClear => '\u{e53c}',
        LeakAdd => '\u{e3f8}',
        LeakRemove => '\u{e3f9}',
        Lens => '\u{e3fa}',
        LibraryAdd => '\u{e02e}',
        LibraryBooks => '\u{e02f}',
        LibraryMusic => '\u{e030}',
        LightbulbOutline => '\u{e90f}',
        LineStyle => '\u{e919}',
        LineWeight => '\u{e91a}',
        LinearScale => '\u{e260}',
        Link => '\u{e157}',
        LinkedCamera => '\u{e438}',
        List => '\u{e896}',
        LiveHelp => '\u{e0c6}',
        LiveTv => '\u{e639}',
        LocalActivity => '\u{e53f}',
        LocalAirport => '\u{e53d}',
        LocalAtm => '\u{e53e}',
        LocalBar => '\u{e540}',
        LocalCafe => '\u{e541}',
        LocalCarWash => '\u{e542}',
        LocalConvenienceStore => '\u{e543}',
        LocalDining => '\u{e556}',
        LocalDrink => '\u{e544}',
        LocalFlorist => '\u{e545}',
        LocalGasStation => '\u{e546}',
        LocalGroceryStore => '\u{e547}',
        LocalHospital => '\u{e548}',
        LocalHotel => '\u{e549}',
        LocalLaundryService => '\u{e54a}',
        LocalLibrary => '\u{e54b}',
        LocalMall => '\u{e54c}',
        LocalMovies => '\u{e54d}',
        LocalOffer => '\u{e54e}',
        LocalParking => '\u{e54f}',
        LocalPharmacy => '\u{e550}',
        LocalPhone => '\u{e551}',
        LocalPizza => '\u{e552}',
        LocalPlay => '\u{e553}',
        LocalPostOffice => '\u{e554}',
        LocalPrintshop => '\u{e555}',
        LocalSee => '\u{e557}',
        LocalShipping => '\u{e558}',
        LocalTaxi => '\u{e559}',
        LocationCity => '\u{e7f1}',
        LocationDisabled => '\u{e1b6}',
        LocationOff => '\u{e0c7}',
        LocationOn => '\u{e0c8}',
        LocationSearching => '\u{e1b7}',
        Lock => '\u{e897}',
        LockOpen => '\u{e898}',
        LockOutline => '\u{e899}',
        Looks => '\u{e3fc}',
        Looks3 => '\u{e3fb}',
        Looks4 => '\u{e3fd}',
        Looks5 => '\u{e3fe}',
        Looks6 => '\u{e3ff}',
        LooksOne => '\u{e400}',
        LooksTwo => '\u{e401}',
        Loop => '\u{e028}',
        Loupe => '\u{e402}',
        LowPriority => '\u{e16d}',
        Loyalty => '\u{e89a}',
        Mail => '\u{e158}',
        MailOutline => '\u{e0e1}',
        Map => '\u{e55b}',
        Markunread => '\u{e159}',
        MarkunreadMailbox => '\u{e89b}',
        Memory => '\u{e322}',
        Menu => '\u{e5d2}',
        MergeType => '\u{e252}',
        Message => '\u{e0c9}',
        Mic => '\u{e029}',
        MicNone => '\u{e02a}',
        MicOff => '\u{e02b}',
        Mms => '\u{e618}',
        ModeComment => '\u{e253}',
        ModeEdit => '\u{e254}',
        MonetizationOn => '\u{e263}',
        MoneyOff => '\u{e25c}',
        MonochromePhotos => '\u{e403}',
        Mood => '\u{e7f2}',
        MoodBad => '\u{e7f3}',
        More => '\u{e619}',
        MoreHoriz => '\u{e5d3}',
        MoreVert => '\u{e5d4}',
        Motorcycle => '\u{e91b}',
        Mouse => '\u{e323}',
        MoveToInbox => '\u{e168}',
        Movie => '\u{e02c}',
        MovieCreation => '\u{e404}',
        MovieFilter => '\u{e43a}',
        MultilineChart => '\u{e6df}',
        MusicNote => '\u{e405}',
        MusicVideo => '\u{e063}',
        MyLocation => '\u{e55c}',
        Nature => '\u{e406}',
        NaturePeople => '\u{e407}',
        NavigateBefore => '\u{e408}',
        NavigateNext => '\u{e409}',
        Navigation => '\u{e55d}',
        NearMe => '\u{e569}',
        NetworkCell => '\u{e1b9}',
        NetworkCheck => '\u{e640}',
        NetworkLocked => '\u{e61a}',
        NetworkWifi => '\u{e1ba}',
        NewReleases => '\u{e031}',
        NextWeek => '\u{e16a}',
        Nfc => '\u{e1bb}',
        NoEncryption => '\u{e641}',
        NoSim => '\u{e0cc}',
        NotInterested => '\u{e033}',
        Note => '\u{e06f}',
        NoteAdd => '\u{e89c}',
        Notifications => '\u{e7f4}',
        NotificationsActive => '\u{e7f7}',
        NotificationsNone => '\u{e7f5}',
        NotificationsOff => '\u{e7f6}',
        NotificationsPaused => '\u{e7f8}',
        OfflinePin => '\u{e90a}',
        OndemandVideo => '\u{e63a}',
        Opacity => '\u{e91c}',
        OpenInBrowser => '\u{e89d}',
        OpenInNew => '\u{e89e}',
        OpenWith => '\u{e89f}',
        Pages => '\u{e7f9}',
        Pageview => '\u{e8a0}',
        Palette => '\u{e40a}',
        PanTool => '\u{e925}',
        Panorama => '\u{e40b}',
        PanoramaFishEye => '\u{e40c}',
        PanoramaHorizontal => '\u{e40d}',
        PanoramaVertical => '\u{e40e}',
        PanoramaWideAngle => '\u{e40f}',
        PartyMode => '\u{e7fa}',
        Pause => '\u{e034}',
        PauseCircleFilled => '\u{e035}',
        PauseCircleOutline => '\u{e036}',
        Payment => '\u{e8a1}',
        People => '\u{e7fb}',
        PeopleOutline => '\u{e7fc}',
        PermCameraMic => '\u{e8a2}',
        PermContactCalendar => '\u{e8a3}',
        PermDataSetting => '\u{e8a4}',
        PermDeviceInformation => '\u{e8a5}',
        PermIdentity => '\u{e8a6}',
        PermMedia => '\u{e8a7}',
        PermPhoneMsg => '\u{e8a8}',
        PermScanWifi => '\u{e8a9}',
        Person => '\u{e7fd}',
        PersonAdd => '\u{e7fe}',
        PersonOutline => '\u{e7ff}',
        PersonPin => '\u{e55a}',
        PersonPinCircle => '\u{e56a}',
        PersonalVideo => '\u{e63b}',
        Pets => '\u{e91d}',
        Phone => '\u{e0cd}',
        PhoneAndroid => '\u{e324}',
        PhoneBluetoothSpeaker => '\u{e61b}',
        PhoneForwarded => '\u{e61c}',
        PhoneInTalk => '\u{e61d}',
        PhoneIphone => '\u{e325}',
        PhoneLocked => '\u{e61e}',
        PhoneMissed => '\u{e61f}',
        PhonePaused => '\u{e620}',
        Phonelink => '\u{e326}',
        PhonelinkErase => '\u{e0db}',
        PhonelinkLock => '\u{e0dc}',
        PhonelinkOff => '\u{e327}',
        PhonelinkRing => '\u{e0dd}',
        PhonelinkSetup => '\u{e0de}',
        Photo => '\u{e410}',
        PhotoAlbum => '\u{e411}',
        PhotoCamera => '\u{e412}',
        PhotoFilter => '\u{e43b}',
        PhotoLibrary => '\u{e413}',
        PhotoSizeSelectActual => '\u{e432}',
        PhotoSizeSelectLarge => '\u{e433}',
        PhotoSizeSelectSmall => '\u{e434}',
        PictureAsPdf => '\u{e415}',
        PictureInPicture => '\u{e8aa}',
        PictureInPictureAlt => '\u{e911}',
        PieChart => '\u{e6c4}',
        PieChartOutlined => '\u{e6c5}',
        PinDrop => '\u{e55e}',
        Place => '\u{e55f}',
        PlayArrow => '\u{e037}',
        PlayCircleFilled => '\u{e038}',
        PlayCircleOutline => '\u{e039}',
        PlayForWork => '\u{e906}',
        PlaylistAdd => '\u{e03b}',
        PlaylistAddCheck => '\u{e065}',
        PlaylistPlay => '\u{e05f}',
        PlusOne => '\u{e800}',
        Poll => '\u{e801}',
        Polymer => '\u{e8ab}',
        Pool => '\u{eb48}',
        PortableWifiOff => '\u{e0ce}',
        Portrait => '\u{e416}',
        Power => '\u{e63c}',
        PowerInput => '\u{e336}',
        PowerSettingsNew => '\u{e8ac}',
        PregnantWoman => '\u{e91e}',
        PresentToAll => '\u{e0df}',
        Print => '\u{e8ad}',
        PriorityHigh => '\u{e645}',
        Public => '\u{e80b}',
        Publish => '\u{e255}',
        QueryBuilder => '\u{e8ae}',
        QuestionAnswer => '\u{e8af}',
        Queue => '\u{e03c}',
        QueueMusic => '\u{e03d}',
        QueuePlayNext => '\u{e066}',
        Radio => '\u{e03e}',
        RadioButtonChecked => '\u{e837}',
        RadioButtonUnchecked => '\u{e836}',
        RateReview => '\u{e560}',
        Receipt => '\u{e8b0}',
        RecentActors => '\u{e03f}',
        RecordVoiceOver => '\u{e91f}',
        Redeem => '\u{e8b1}',
        Redo => '\u{e15a}',
        Refresh => '\u{e5d5}',
        Remove => '\u{e15b}',
        RemoveCircle => '\u{e15c}',
        RemoveCircleOutline => '\u{e15d}',
        RemoveFromQueue => '\u{e067}',
        RemoveRedEye => '\u{e417}',
        RemoveShoppingCart => '\u{e928}',
        Reorder => '\u{e8fe}',
        Repeat => '\u{e040}',
        RepeatOne => '\u{e041}',
        Replay => '\u{e042}',
        Replay10 => '\u{e059}',
        Replay30 => '\u{e05a}',
        Replay5 => '\u{e05b}',
        Reply => '\u{e15e}',
        ReplyAll => '\u{e15f}',
        Report => '\u{e160}',
        ReportProblem => '\u{e8b2}',
        Restaurant => '\u{e56c}',
        RestaurantMenu => '\u{e561}',
        Restore => '\u{e8b3}',
        RestorePage => '\u{e929}',
        RingVolume => '\u{e0d1}',
        Room => '\u{e8b4}',
        RoomService => '\u{eb49}',
        Rotate90DegreesCcw => '\u{e418}',
        RotateLeft => '\u{e419}',
        RotateRight => '\u{e41a}',
        RoundedCorner => '\u{e920}',
        Router => '\u{e328}',
        Rowing => '\u{e921}',
        RssFeed => '\u{e0e5}',
        RvHookup => '\u{e642}',
        Satellite => '\u{e562}',
        Save => '\u{e161}',
        Scanner => '\u{e329}',
        Schedule => '\u{e8b5}',
        School => '\u{e80c}',
        ScreenLockLandscape => '\u{e1be}',
        ScreenLockPortrait => '\u{e1bf}',
        ScreenLockRotation => '\u{e1c0}',
        ScreenRotation => '\u{e1c1}',
        ScreenShare => '\u{e0e2}',
        SdCard => '\u{e623}',
        SdStorage => '\u{e1c2}',
        Search => '\u{e8b6}',
        Security => '\u{e32a}',
        SelectAll => '\u{e162}',
        Send => '\u{e163}',
        SentimentDissatisfied => '\u{e811}',
        SentimentNeutral => '\u{e812}',
        SentimentSatisfied => '\u{e813}',
        SentimentVeryDissatisfied => '\u{e814}',
        SentimentVerySatisfied => '\u{e815}',
        Settings => '\u{e8b8}',
        SettingsApplications => '\u{e8b9}',
        SettingsBackupRestore => '\u{e8ba}',
        SettingsBluetooth => '\u{e8bb}',
        SettingsBrightness => '\u{e8bd}',
        SettingsCell => '\u{e8bc}',
        SettingsEthernet => '\u{e8be}',
        SettingsInputAntenna => '\u{e8bf}',
        SettingsInputComponent => '\u{e8c0}',
        SettingsInputComposite => '\u{e8c1}',
        SettingsInputHdmi => '\u{e8c2}',
        SettingsInputSvideo => '\u{e8c3}',
        SettingsOverscan => '\u{e8c4}',
        SettingsPhone => '\u{e8c5}',
        SettingsPower => '\u{e8c6}',
        SettingsRemote => '\u{e8c7}',
        SettingsSystemDaydream => '\u{e1c3}',
        SettingsVoice => '\u{e8c8}',
        Share => '\u{e80d}',
        Shop => '\u{e8c9}',
        ShopTwo => '\u{e8ca}',
        ShoppingBasket => '\u{e8cb}',
        ShoppingCart => '\u{e8cc}',
        ShortText => '\u{e261}',
        ShowChart => '\u{e6e1}',
        Shuffle => '\u{e043}',
        SignalCellular4Bar => '\u{e1c8}',
        SignalCellularConnectedNoInternet4Bar => '\u{e1cd}',
        SignalCellularNoSim => '\u{e1ce}',
        SignalCellularNull => '\u{e1cf}',
        SignalCellularOff => '\u{e1d0}',
        SignalWifi4Bar => '\u{e1d8}',
        SignalWifi4BarLock => '\u{e1d9}',
        SignalWifiOff => '\u{e1da}',
        SimCard => '\u{e32b}',
        SimCardAlert => '\u{e624}',
        SkipNext => '\u{e044}',
        SkipPrevious => '\u{e045}',
        Slideshow => '\u{e41b}',
        SlowMotionVideo => '\u{e068}',
        Smartphone => '\u{e32c}',
        SmokeFree => '\u{eb4a}',
        SmokingRooms => '\u{eb4b}',
        Sms => '\u{e625}',
        SmsFailed => '\u{e626}',
        Snooze => '\u{e046}',
        Sort => '\u{e164}',
        SortByAlpha => '\u{e053}',
        Spa => '\u{eb4c}',
        SpaceBar => '\u{e256}',
        Speaker => '\u{e32d}',
        SpeakerGroup => '\u{e32e}',
        SpeakerNotes => '\u{e8cd}',
        SpeakerNotesOff => '\u{e92a}',
        SpeakerPhone => '\u{e0d2}',
        Spellcheck => '\u{e8ce}',
        Star => '\u{e838}',
        StarBorder => '\u{e83a}',
        StarHalf => '\u{e839}',
        Stars => '\u{e8d0}',
        StayCurrentLandscape => '\u{e0d3}',
        StayCurrentPortrait => '\u{e0d4}',
        StayPrimaryLandscape => '\u{e0d5}',
        StayPrimaryPortrait => '\u{e0d6}',
        Stop => '\u{e047}',
        StopScreenShare => '\u{e0e3}',
        Storage => '\u{e1db}',
        Store => '\u{e8d1}',
        StoreMallDirectory => '\u{e563}',
        Straighten => '\u{e41c}',
        Streetview => '\u{e56e}',
        StrikethroughS => '\u{e257}',
        Style => '\u{e41d}',
        SubdirectoryArrowLeft => '\u{e5d9}',
        SubdirectoryArrowRight => '\u{e5da}',
        Subject => '\u{e8d2}',
        Subscriptions => '\u{e064}',
        Subtitles => '\u{e048}',
        Subway => '\u{e56f}',
        SupervisorAccount => '\u{e8d3}',
        SurroundSound => '\u{e049}',
        SwapCalls => '\u{e0d7}',
        SwapHoriz => '\u{e8d4}',
        SwapVert => '\u{e8d5}',
        SwapVerticalCircle => '\u{e8d6}',
        SwitchCamera => '\u{e41e}',
        SwitchVideo => '\u{e41f}',
        Sync => '\u{e627}',
        SyncDisabled => '\u{e628}',
        SyncProblem => '\u{e629}',
        SystemUpdate => '\u{e62a}',
        SystemUpdateAlt => '\u{e8d7}',
        Tab => '\u{e8d8}',
        TabUnselected => '\u{e8d9}',
        Tablet => '\u{e32f}',
        TabletAndroid => '\u{e330}',
        TabletMac => '\u{e331}',
        TagFaces => '\u{e420}',
        TapAndPlay => '\u{e62b}',
        Terrain => '\u{e564}',
        TextFields => '\u{e262}',
        TextFormat => '\u{e165}',
        Textsms => '\u{e0d8}',
        Texture => '\u{e421}',
        Theaters => '\u{e8da}',
        ThumbDown => '\u{e8db}',
        ThumbUp => '\u{e8dc}',
        ThumbsUpDown => '\u{e8dd}',
        TimeToLeave => '\u{e62c}',
        Timelapse => '\u{e422}',
        Timeline => '\u{e922}',
        Timer => '\u{e425}',
        Timer10 => '\u{e423}',
        Timer3 => '\u{e424}',
        TimerOff => '\u{e426}',
        Title => '\u{e264}',
        Toc => '\u{e8de}',
        Today => '\u{e8df}',
        Toll => '\u{e8e0}',
        Tonality => '\u{e427}',
        TouchApp => '\u{e913}',
        Toys => '\u{e332}',
        TrackChanges => '\u{e8e1}',
        Traffic => '\u{e565}',
        Train => '\u{e570}',
        Tram => '\u{e571}',
        TransferWithinAStation => '\u{e572}',
        Transform => '\u{e428}',
        Translate => '\u{e8e2}',
        TrendingDown => '\u{e8e3}',
        TrendingFlat => '\u{e8e4}',
        TrendingUp => '\u{e8e5}',
        Tune => '\u{e429}',
        TurnedIn => '\u{e8e6}',
        TurnedInNot => '\u{e8e7}',
        Tv => '\u{e333}',
        Unarchive => '\u{e169}',
        Undo => '\u{e166}',
        UnfoldLess => '\u{e5d6}',
        UnfoldMore => '\u{e5d7}',
        Update => '\u{e923}',
        Usb => '\u{e1e0}',
        VerifiedUser => '\u{e8e8}',
        VerticalAlignBottom => '\u{e258}',
        VerticalAlignCenter => '\u{e259}',
        VerticalAlignTop => '\u{e25a}',
        Vibration => '\u{e62d}',
        VideoCall => '\u{e070}',
        VideoLabel => '\u{e071}',
        VideoLibrary => '\u{e04a}',
        Videocam => '\u{e04b}',
        VideocamOff => '\u{e04c}',
        VideogameAsset => '\u{e338}',
        ViewAgenda => '\u{e8e9}',
        ViewArray => '\u{e8ea}',
        ViewCarousel => '\u{e8eb}',
        ViewColumn => '\u{e8ec}',
        ViewComfy => '\u{e42a}',
        ViewCompact => '\u{e42b}',
        ViewDay => '\u{e8ed}',
        ViewHeadline => '\u{e8ee}',
        ViewList => '\u{e8ef}',
        ViewModule => '\u{e8f0}',
        ViewQuilt => '\u{e8f1}',
        ViewStream => '\u{e8f2}',
        ViewWeek => '\u{e8f3}',
        Vignette => '\u{e435}',
        Visibility => '\u{e8f4}',
        VisibilityOff => '\u{e8f5}',
        VoiceChat => '\u{e62e}',
        Voicemail => '\u{e0d9}',
        VolumeDown => '\u{e04d}',
        VolumeMute => '\u{e04e}',
        VolumeOff => '\u{e04f}',
        VolumeUp => '\u{e050}',
        VpnKey => '\u{e0da}',
        VpnLock => '\u{e62f}',
        Wallpaper => '\u{e1bc}',
        Warning => '\u{e002}',
        Watch => '\u{e334}',
        WatchLater => '\u{e924}',
        WbAuto => '\u{e42c}',
        WbCloudy => '\u{e42d}',
        WbIncandescent => '\u{e42e}',
        WbIridescent => '\u{e436}',
        WbSunny => '\u{e430}',
        Wc => '\u{e63d}',
        Web => '\u{e051}',
        WebAsset => '\u{e069}',
        Weekend => '\u{e16b}',
        Whatshot => '\u{e80e}',
        Widgets => '\u{e1bd}',
        Wifi => '\u{e63e}',
        WifiLock => '\u{e1e1}',
        WifiTethering => '\u{e1e2}',
        Work => '\u{e8f9}',
        WrapText => '\u{e25b}',
        YoutubeSearchedFor => '\u{e8fa}',
        ZoomIn => '\u{e8ff}',
        ZoomOut => '\u{e900}',
        ZoomOutMap => '\u{e56b}',
    }
}
impl From<Icon> for char {
    fn from(icon: Icon) -> char {
        icon_to_char(icon)
    }
}

/// Material icons font (`MaterialIcons-Regular.ttf`), licensed under the Apache 2.0 license
/// While attribution is not strictly required, it is appreciated.
/// See https://github.com/google/material-design-icons for more information
pub const FONT: &[u8] = include_bytes!("../assets/MaterialIcons-Regular.ttf");

use std::fmt;
impl fmt::Display for Icon {
    fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
        write!(f, "{}", icon_to_char(*self))
    }
}

/// Get icon HTML name
pub fn icon_to_html_name(icon: &Icon) -> &'static str {
    use self::Icon::*;
    match *icon {
        Rotation3d => "3d_rotation",
        AcUnit => "ac_unit",
        AccessAlarm => "access_alarm",
        AccessAlarms => "access_alarms",
        AccessTime => "access_time",
        Accessibility => "accessibility",
        Accessible => "accessible",
        AccountBalance => "account_balance",
        AccountBalanceWallet => "account_balance_wallet",
        AccountBox => "account_box",
        AccountCircle => "account_circle",
        Adb => "adb",
        Add => "add",
        AddAPhoto => "add_a_photo",
        AddAlarm => "add_alarm",
        AddAlert => "add_alert",
        AddBox => "add_box",
        AddCircle => "add_circle",
        AddCircleOutline => "add_circle_outline",
        AddLocation => "add_location",
        AddShoppingCart => "add_shopping_cart",
        AddToPhotos => "add_to_photos",
        AddToQueue => "add_to_queue",
        Adjust => "adjust",
        AirlineSeatFlat => "airline_seat_flat",
        AirlineSeatFlatAngled => "airline_seat_flat_angled",
        AirlineSeatIndividualSuite => "airline_seat_individual_suite",
        AirlineSeatLegroomExtra => "airline_seat_legroom_extra",
        AirlineSeatLegroomNormal => "airline_seat_legroom_normal",
        AirlineSeatLegroomReduced => "airline_seat_legroom_reduced",
        AirlineSeatReclineExtra => "airline_seat_recline_extra",
        AirlineSeatReclineNormal => "airline_seat_recline_normal",
        AirplanemodeActive => "airplanemode_active",
        AirplanemodeInactive => "airplanemode_inactive",
        Airplay => "airplay",
        AirportShuttle => "airport_shuttle",
        Alarm => "alarm",
        AlarmAdd => "alarm_add",
        AlarmOff => "alarm_off",
        AlarmOn => "alarm_on",
        Album => "album",
        AllInclusive => "all_inclusive",
        AllOut => "all_out",
        Android => "android",
        Announcement => "announcement",
        Apps => "apps",
        Archive => "archive",
        ArrowBack => "arrow_back",
        ArrowDownward => "arrow_downward",
        ArrowDropDown => "arrow_drop_down",
        ArrowDropDownCircle => "arrow_drop_down_circle",
        ArrowDropUp => "arrow_drop_up",
        ArrowForward => "arrow_forward",
        ArrowUpward => "arrow_upward",
        ArtTrack => "art_track",
        AspectRatio => "aspect_ratio",
        Assessment => "assessment",
        Assignment => "assignment",
        AssignmentInd => "assignment_ind",
        AssignmentLate => "assignment_late",
        AssignmentReturn => "assignment_return",
        AssignmentReturned => "assignment_returned",
        AssignmentTurnedIn => "assignment_turned_in",
        Assistant => "assistant",
        AssistantPhoto => "assistant_photo",
        AttachFile => "attach_file",
        AttachMoney => "attach_money",
        Attachment => "attachment",
        Audiotrack => "audiotrack",
        Autorenew => "autorenew",
        AvTimer => "av_timer",
        Backspace => "backspace",
        Backup => "backup",
        BatteryAlert => "battery_alert",
        BatteryChargingFull => "battery_charging_full",
        BatteryFull => "battery_full",
        BatteryStd => "battery_std",
        BatteryUnknown => "battery_unknown",
        BeachAccess => "beach_access",
        Beenhere => "beenhere",
        Block => "block",
        Bluetooth => "bluetooth",
        BluetoothAudio => "bluetooth_audio",
        BluetoothConnected => "bluetooth_connected",
        BluetoothDisabled => "bluetooth_disabled",
        BluetoothSearching => "bluetooth_searching",
        BlurCircular => "blur_circular",
        BlurLinear => "blur_linear",
        BlurOff => "blur_off",
        BlurOn => "blur_on",
        Book => "book",
        Bookmark => "bookmark",
        BookmarkBorder => "bookmark_border",
        BorderAll => "border_all",
        BorderBottom => "border_bottom",
        BorderClear => "border_clear",
        BorderColor => "border_color",
        BorderHorizontal => "border_horizontal",
        BorderInner => "border_inner",
        BorderLeft => "border_left",
        BorderOuter => "border_outer",
        BorderRight => "border_right",
        BorderStyle => "border_style",
        BorderTop => "border_top",
        BorderVertical => "border_vertical",
        BrandingWatermark => "branding_watermark",
        Brightness1 => "brightness_1",
        Brightness2 => "brightness_2",
        Brightness3 => "brightness_3",
        Brightness4 => "brightness_4",
        Brightness5 => "brightness_5",
        Brightness6 => "brightness_6",
        Brightness7 => "brightness_7",
        BrightnessAuto => "brightness_auto",
        BrightnessHigh => "brightness_high",
        BrightnessLow => "brightness_low",
        BrightnessMedium => "brightness_medium",
        BrokenImage => "broken_image",
        Brush => "brush",
        BubbleChart => "bubble_chart",
        BugReport => "bug_report",
        Build => "build",
        BurstMode => "burst_mode",
        Business => "business",
        BusinessCenter => "business_center",
        Cached => "cached",
        Cake => "cake",
        Call => "call",
        CallEnd => "call_end",
        CallMade => "call_made",
        CallMerge => "call_merge",
        CallMissed => "call_missed",
        CallMissedOutgoing => "call_missed_outgoing",
        CallReceived => "call_received",
        CallSplit => "call_split",
        CallToAction => "call_to_action",
        Camera => "camera",
        CameraAlt => "camera_alt",
        CameraEnhance => "camera_enhance",
        CameraFront => "camera_front",
        CameraRear => "camera_rear",
        CameraRoll => "camera_roll",
        Cancel => "cancel",
        CardGiftcard => "card_giftcard",
        CardMembership => "card_membership",
        CardTravel => "card_travel",
        Casino => "casino",
        Cast => "cast",
        CastConnected => "cast_connected",
        CenterFocusStrong => "center_focus_strong",
        CenterFocusWeak => "center_focus_weak",
        ChangeHistory => "change_history",
        Chat => "chat",
        ChatBubble => "chat_bubble",
        ChatBubbleOutline => "chat_bubble_outline",
        Check => "check",
        CheckBox => "check_box",
        CheckBoxOutlineBlank => "check_box_outline_blank",
        CheckCircle => "check_circle",
        ChevronLeft => "chevron_left",
        ChevronRight => "chevron_right",
        ChildCare => "child_care",
        ChildFriendly => "child_friendly",
        ChromeReaderMode => "chrome_reader_mode",
        Class => "class",
        Clear => "clear",
        ClearAll => "clear_all",
        Close => "close",
        ClosedCaption => "closed_caption",
        Cloud => "cloud",
        CloudCircle => "cloud_circle",
        CloudDone => "cloud_done",
        CloudDownload => "cloud_download",
        CloudOff => "cloud_off",
        CloudQueue => "cloud_queue",
        CloudUpload => "cloud_upload",
        Code => "code",
        Collections => "collections",
        CollectionsBookmark => "collections_bookmark",
        ColorLens => "color_lens",
        Colorize => "colorize",
        Comment => "comment",
        Compare => "compare",
        CompareArrows => "compare_arrows",
        Computer => "computer",
        ConfirmationNumber => "confirmation_number",
        ContactMail => "contact_mail",
        ContactPhone => "contact_phone",
        Contacts => "contacts",
        ContentCopy => "content_copy",
        ContentCut => "content_cut",
        ContentPaste => "content_paste",
        ControlPoint => "control_point",
        ControlPointDuplicate => "control_point_duplicate",
        Copyright => "copyright",
        Create => "create",
        CreateNewFolder => "create_new_folder",
        CreditCard => "credit_card",
        Crop => "crop",
        Crop169 => "crop_16_9",
        Crop32 => "crop_3_2",
        Crop54 => "crop_5_4",
        Crop75 => "crop_7_5",
        CropDin => "crop_din",
        CropFree => "crop_free",
        CropLandscape => "crop_landscape",
        CropOriginal => "crop_original",
        CropPortrait => "crop_portrait",
        CropRotate => "crop_rotate",
        CropSquare => "crop_square",
        Dashboard => "dashboard",
        DataUsage => "data_usage",
        DateRange => "date_range",
        Dehaze => "dehaze",
        Delete => "delete",
        DeleteForever => "delete_forever",
        DeleteSweep => "delete_sweep",
        Description => "description",
        DesktopMac => "desktop_mac",
        DesktopWindows => "desktop_windows",
        Details => "details",
        DeveloperBoard => "developer_board",
        DeveloperMode => "developer_mode",
        DeviceHub => "device_hub",
        Devices => "devices",
        DevicesOther => "devices_other",
        DialerSip => "dialer_sip",
        Dialpad => "dialpad",
        Directions => "directions",
        DirectionsBike => "directions_bike",
        DirectionsBoat => "directions_boat",
        DirectionsBus => "directions_bus",
        DirectionsCar => "directions_car",
        DirectionsRailway => "directions_railway",
        DirectionsRun => "directions_run",
        DirectionsSubway => "directions_subway",
        DirectionsTransit => "directions_transit",
        DirectionsWalk => "directions_walk",
        DiscFull => "disc_full",
        Dns => "dns",
        DoNotDisturb => "do_not_disturb",
        DoNotDisturbAlt => "do_not_disturb_alt",
        DoNotDisturbOff => "do_not_disturb_off",
        DoNotDisturbOn => "do_not_disturb_on",
        Dock => "dock",
        Domain => "domain",
        Done => "done",
        DoneAll => "done_all",
        DonutLarge => "donut_large",
        DonutSmall => "donut_small",
        Drafts => "drafts",
        DragHandle => "drag_handle",
        DriveEta => "drive_eta",
        Dvr => "dvr",
        Edit => "edit",
        EditLocation => "edit_location",
        Eject => "eject",
        Email => "email",
        EnhancedEncryption => "enhanced_encryption",
        Equalizer => "equalizer",
        Error => "error",
        ErrorOutline => "error_outline",
        EuroSymbol => "euro_symbol",
        EvStation => "ev_station",
        Event => "event",
        EventAvailable => "event_available",
        EventBusy => "event_busy",
        EventNote => "event_note",
        EventSeat => "event_seat",
        ExitToApp => "exit_to_app",
        ExpandLess => "expand_less",
        ExpandMore => "expand_more",
        Explicit => "explicit",
        Explore => "explore",
        Exposure => "exposure",
        ExposureNeg1 => "exposure_neg_1",
        ExposureNeg2 => "exposure_neg_2",
        ExposurePlus1 => "exposure_plus_1",
        ExposurePlus2 => "exposure_plus_2",
        ExposureZero => "exposure_zero",
        Extension => "extension",
        Face => "face",
        FastForward => "fast_forward",
        FastRewind => "fast_rewind",
        Favorite => "favorite",
        FavoriteBorder => "favorite_border",
        FeaturedPlayList => "featured_play_list",
        FeaturedVideo => "featured_video",
        Feedback => "feedback",
        FiberDvr => "fiber_dvr",
        FiberManualRecord => "fiber_manual_record",
        FiberNew => "fiber_new",
        FiberPin => "fiber_pin",
        FiberSmartRecord => "fiber_smart_record",
        FileDownload => "file_download",
        FileUpload => "file_upload",
        Filter => "filter",
        Filter1 => "filter_1",
        Filter2 => "filter_2",
        Filter3 => "filter_3",
        Filter4 => "filter_4",
        Filter5 => "filter_5",
        Filter6 => "filter_6",
        Filter7 => "filter_7",
        Filter8 => "filter_8",
        Filter9 => "filter_9",
        Filter9Plus => "filter_9_plus",
        FilterBAndW => "filter_b_and_w",
        FilterCenterFocus => "filter_center_focus",
        FilterDrama => "filter_drama",
        FilterFrames => "filter_frames",
        FilterHdr => "filter_hdr",
        FilterList => "filter_list",
        FilterNone => "filter_none",
        FilterTiltShift => "filter_tilt_shift",
        FilterVintage => "filter_vintage",
        FindInPage => "find_in_page",
        FindReplace => "find_replace",
        Fingerprint => "fingerprint",
        FirstPage => "first_page",
        FitnessCenter => "fitness_center",
        Flag => "flag",
        Flare => "flare",
        FlashAuto => "flash_auto",
        FlashOff => "flash_off",
        FlashOn => "flash_on",
        Flight => "flight",
        FlightLand => "flight_land",
        FlightTakeoff => "flight_takeoff",
        Flip => "flip",
        FlipToBack => "flip_to_back",
        FlipToFront => "flip_to_front",
        Folder => "folder",
        FolderOpen => "folder_open",
        FolderShared => "folder_shared",
        FolderSpecial => "folder_special",
        FontDownload => "font_download",
        FormatAlignCenter => "format_align_center",
        FormatAlignJustify => "format_align_justify",
        FormatAlignLeft => "format_align_left",
        FormatAlignRight => "format_align_right",
        FormatBold => "format_bold",
        FormatClear => "format_clear",
        FormatColorFill => "format_color_fill",
        FormatColorReset => "format_color_reset",
        FormatColorText => "format_color_text",
        FormatIndentDecrease => "format_indent_decrease",
        FormatIndentIncrease => "format_indent_increase",
        FormatItalic => "format_italic",
        FormatLineSpacing => "format_line_spacing",
        FormatListBulleted => "format_list_bulleted",
        FormatListNumbered => "format_list_numbered",
        FormatPaint => "format_paint",
        FormatQuote => "format_quote",
        FormatShapes => "format_shapes",
        FormatSize => "format_size",
        FormatStrikethrough => "format_strikethrough",
        FormatTextdirectionLToR => "format_textdirection_l_to_r",
        FormatTextdirectionRToL => "format_textdirection_r_to_l",
        FormatUnderlined => "format_underlined",
        Forum => "forum",
        Forward => "forward",
        Forward10 => "forward_10",
        Forward30 => "forward_30",
        Forward5 => "forward_5",
        FreeBreakfast => "free_breakfast",
        Fullscreen => "fullscreen",
        FullscreenExit => "fullscreen_exit",
        Functions => "functions",
        GTranslate => "g_translate",
        Gamepad => "gamepad",
        Games => "games",
        Gavel => "gavel",
        Gesture => "gesture",
        GetApp => "get_app",
        Gif => "gif",
        GolfCourse => "golf_course",
        GpsFixed => "gps_fixed",
        GpsNotFixed => "gps_not_fixed",
        GpsOff => "gps_off",
        Grade => "grade",
        Gradient => "gradient",
        Grain => "grain",
        GraphicEq => "graphic_eq",
        GridOff => "grid_off",
        GridOn => "grid_on",
        Group => "group",
        GroupAdd => "group_add",
        GroupWork => "group_work",
        Hd => "hd",
        HdrOff => "hdr_off",
        HdrOn => "hdr_on",
        HdrStrong => "hdr_strong",
        HdrWeak => "hdr_weak",
        Headset => "headset",
        HeadsetMic => "headset_mic",
        Healing => "healing",
        Hearing => "hearing",
        Help => "help",
        HelpOutline => "help_outline",
        HighQuality => "high_quality",
        Highlight => "highlight",
        HighlightOff => "highlight_off",
        History => "history",
        Home => "home",
        HotTub => "hot_tub",
        Hotel => "hotel",
        HourglassEmpty => "hourglass_empty",
        HourglassFull => "hourglass_full",
        Http => "http",
        Https => "https",
        Image => "image",
        ImageAspectRatio => "image_aspect_ratio",
        ImportContacts => "import_contacts",
        ImportExport => "import_export",
        ImportantDevices => "important_devices",
        Inbox => "inbox",
        IndeterminateCheckBox => "indeterminate_check_box",
        Info => "info",
        InfoOutline => "info_outline",
        Input => "input",
        InsertChart => "insert_chart",
        InsertComment => "insert_comment",
        InsertDriveFile => "insert_drive_file",
        InsertEmoticon => "insert_emoticon",
        InsertInvitation => "insert_invitation",
        InsertLink => "insert_link",
        InsertPhoto => "insert_photo",
        InvertColors => "invert_colors",
        InvertColorsOff => "invert_colors_off",
        Iso => "iso",
        Keyboard => "keyboard",
        KeyboardArrowDown => "keyboard_arrow_down",
        KeyboardArrowLeft => "keyboard_arrow_left",
        KeyboardArrowRight => "keyboard_arrow_right",
        KeyboardArrowUp => "keyboard_arrow_up",
        KeyboardBackspace => "keyboard_backspace",
        KeyboardCapslock => "keyboard_capslock",
        KeyboardHide => "keyboard_hide",
        KeyboardReturn => "keyboard_return",
        KeyboardTab => "keyboard_tab",
        KeyboardVoice => "keyboard_voice",
        Kitchen => "kitchen",
        Label => "label",
        LabelOutline => "label_outline",
        Landscape => "landscape",
        Language => "language",
        Laptop => "laptop",
        LaptopChromebook => "laptop_chromebook",
        LaptopMac => "laptop_mac",
        LaptopWindows => "laptop_windows",
        LastPage => "last_page",
        Launch => "launch",
        Layers => "layers",
        LayersClear => "layers_clear",
        LeakAdd => "leak_add",
        LeakRemove => "leak_remove",
        Lens => "lens",
        LibraryAdd => "library_add",
        LibraryBooks => "library_books",
        LibraryMusic => "library_music",
        LightbulbOutline => "lightbulb_outline",
        LineStyle => "line_style",
        LineWeight => "line_weight",
        LinearScale => "linear_scale",
        Link => "link",
        LinkedCamera => "linked_camera",
        List => "list",
        LiveHelp => "live_help",
        LiveTv => "live_tv",
        LocalActivity => "local_activity",
        LocalAirport => "local_airport",
        LocalAtm => "local_atm",
        LocalBar => "local_bar",
        LocalCafe => "local_cafe",
        LocalCarWash => "local_car_wash",
        LocalConvenienceStore => "local_convenience_store",
        LocalDining => "local_dining",
        LocalDrink => "local_drink",
        LocalFlorist => "local_florist",
        LocalGasStation => "local_gas_station",
        LocalGroceryStore => "local_grocery_store",
        LocalHospital => "local_hospital",
        LocalHotel => "local_hotel",
        LocalLaundryService => "local_laundry_service",
        LocalLibrary => "local_library",
        LocalMall => "local_mall",
        LocalMovies => "local_movies",
        LocalOffer => "local_offer",
        LocalParking => "local_parking",
        LocalPharmacy => "local_pharmacy",
        LocalPhone => "local_phone",
        LocalPizza => "local_pizza",
        LocalPlay => "local_play",
        LocalPostOffice => "local_post_office",
        LocalPrintshop => "local_printshop",
        LocalSee => "local_see",
        LocalShipping => "local_shipping",
        LocalTaxi => "local_taxi",
        LocationCity => "location_city",
        LocationDisabled => "location_disabled",
        LocationOff => "location_off",
        LocationOn => "location_on",
        LocationSearching => "location_searching",
        Lock => "lock",
        LockOpen => "lock_open",
        LockOutline => "lock_outline",
        Looks => "looks",
        Looks3 => "looks_3",
        Looks4 => "looks_4",
        Looks5 => "looks_5",
        Looks6 => "looks_6",
        LooksOne => "looks_one",
        LooksTwo => "looks_two",
        Loop => "loop",
        Loupe => "loupe",
        LowPriority => "low_priority",
        Loyalty => "loyalty",
        Mail => "mail",
        MailOutline => "mail_outline",
        Map => "map",
        Markunread => "markunread",
        MarkunreadMailbox => "markunread_mailbox",
        Memory => "memory",
        Menu => "menu",
        MergeType => "merge_type",
        Message => "message",
        Mic => "mic",
        MicNone => "mic_none",
        MicOff => "mic_off",
        Mms => "mms",
        ModeComment => "mode_comment",
        ModeEdit => "mode_edit",
        MonetizationOn => "monetization_on",
        MoneyOff => "money_off",
        MonochromePhotos => "monochrome_photos",
        Mood => "mood",
        MoodBad => "mood_bad",
        More => "more",
        MoreHoriz => "more_horiz",
        MoreVert => "more_vert",
        Motorcycle => "motorcycle",
        Mouse => "mouse",
        MoveToInbox => "move_to_inbox",
        Movie => "movie",
        MovieCreation => "movie_creation",
        MovieFilter => "movie_filter",
        MultilineChart => "multiline_chart",
        MusicNote => "music_note",
        MusicVideo => "music_video",
        MyLocation => "my_location",
        Nature => "nature",
        NaturePeople => "nature_people",
        NavigateBefore => "navigate_before",
        NavigateNext => "navigate_next",
        Navigation => "navigation",
        NearMe => "near_me",
        NetworkCell => "network_cell",
        NetworkCheck => "network_check",
        NetworkLocked => "network_locked",
        NetworkWifi => "network_wifi",
        NewReleases => "new_releases",
        NextWeek => "next_week",
        Nfc => "nfc",
        NoEncryption => "no_encryption",
        NoSim => "no_sim",
        NotInterested => "not_interested",
        Note => "note",
        NoteAdd => "note_add",
        Notifications => "notifications",
        NotificationsActive => "notifications_active",
        NotificationsNone => "notifications_none",
        NotificationsOff => "notifications_off",
        NotificationsPaused => "notifications_paused",
        OfflinePin => "offline_pin",
        OndemandVideo => "ondemand_video",
        Opacity => "opacity",
        OpenInBrowser => "open_in_browser",
        OpenInNew => "open_in_new",
        OpenWith => "open_with",
        Pages => "pages",
        Pageview => "pageview",
        Palette => "palette",
        PanTool => "pan_tool",
        Panorama => "panorama",
        PanoramaFishEye => "panorama_fish_eye",
        PanoramaHorizontal => "panorama_horizontal",
        PanoramaVertical => "panorama_vertical",
        PanoramaWideAngle => "panorama_wide_angle",
        PartyMode => "party_mode",
        Pause => "pause",
        PauseCircleFilled => "pause_circle_filled",
        PauseCircleOutline => "pause_circle_outline",
        Payment => "payment",
        People => "people",
        PeopleOutline => "people_outline",
        PermCameraMic => "perm_camera_mic",
        PermContactCalendar => "perm_contact_calendar",
        PermDataSetting => "perm_data_setting",
        PermDeviceInformation => "perm_device_information",
        PermIdentity => "perm_identity",
        PermMedia => "perm_media",
        PermPhoneMsg => "perm_phone_msg",
        PermScanWifi => "perm_scan_wifi",
        Person => "person",
        PersonAdd => "person_add",
        PersonOutline => "person_outline",
        PersonPin => "person_pin",
        PersonPinCircle => "person_pin_circle",
        PersonalVideo => "personal_video",
        Pets => "pets",
        Phone => "phone",
        PhoneAndroid => "phone_android",
        PhoneBluetoothSpeaker => "phone_bluetooth_speaker",
        PhoneForwarded => "phone_forwarded",
        PhoneInTalk => "phone_in_talk",
        PhoneIphone => "phone_iphone",
        PhoneLocked => "phone_locked",
        PhoneMissed => "phone_missed",
        PhonePaused => "phone_paused",
        Phonelink => "phonelink",
        PhonelinkErase => "phonelink_erase",
        PhonelinkLock => "phonelink_lock",
        PhonelinkOff => "phonelink_off",
        PhonelinkRing => "phonelink_ring",
        PhonelinkSetup => "phonelink_setup",
        Photo => "photo",
        PhotoAlbum => "photo_album",
        PhotoCamera => "photo_camera",
        PhotoFilter => "photo_filter",
        PhotoLibrary => "photo_library",
        PhotoSizeSelectActual => "photo_size_select_actual",
        PhotoSizeSelectLarge => "photo_size_select_large",
        PhotoSizeSelectSmall => "photo_size_select_small",
        PictureAsPdf => "picture_as_pdf",
        PictureInPicture => "picture_in_picture",
        PictureInPictureAlt => "picture_in_picture_alt",
        PieChart => "pie_chart",
        PieChartOutlined => "pie_chart_outlined",
        PinDrop => "pin_drop",
        Place => "place",
        PlayArrow => "play_arrow",
        PlayCircleFilled => "play_circle_filled",
        PlayCircleOutline => "play_circle_outline",
        PlayForWork => "play_for_work",
        PlaylistAdd => "playlist_add",
        PlaylistAddCheck => "playlist_add_check",
        PlaylistPlay => "playlist_play",
        PlusOne => "plus_one",
        Poll => "poll",
        Polymer => "polymer",
        Pool => "pool",
        PortableWifiOff => "portable_wifi_off",
        Portrait => "portrait",
        Power => "power",
        PowerInput => "power_input",
        PowerSettingsNew => "power_settings_new",
        PregnantWoman => "pregnant_woman",
        PresentToAll => "present_to_all",
        Print => "print",
        PriorityHigh => "priority_high",
        Public => "public",
        Publish => "publish",
        QueryBuilder => "query_builder",
        QuestionAnswer => "question_answer",
        Queue => "queue",
        QueueMusic => "queue_music",
        QueuePlayNext => "queue_play_next",
        Radio => "radio",
        RadioButtonChecked => "radio_button_checked",
        RadioButtonUnchecked => "radio_button_unchecked",
        RateReview => "rate_review",
        Receipt => "receipt",
        RecentActors => "recent_actors",
        RecordVoiceOver => "record_voice_over",
        Redeem => "redeem",
        Redo => "redo",
        Refresh => "refresh",
        Remove => "remove",
        RemoveCircle => "remove_circle",
        RemoveCircleOutline => "remove_circle_outline",
        RemoveFromQueue => "remove_from_queue",
        RemoveRedEye => "remove_red_eye",
        RemoveShoppingCart => "remove_shopping_cart",
        Reorder => "reorder",
        Repeat => "repeat",
        RepeatOne => "repeat_one",
        Replay => "replay",
        Replay10 => "replay_10",
        Replay30 => "replay_30",
        Replay5 => "replay_5",
        Reply => "reply",
        ReplyAll => "reply_all",
        Report => "report",
        ReportProblem => "report_problem",
        Restaurant => "restaurant",
        RestaurantMenu => "restaurant_menu",
        Restore => "restore",
        RestorePage => "restore_page",
        RingVolume => "ring_volume",
        Room => "room",
        RoomService => "room_service",
        Rotate90DegreesCcw => "rotate_90_degrees_ccw",
        RotateLeft => "rotate_left",
        RotateRight => "rotate_right",
        RoundedCorner => "rounded_corner",
        Router => "router",
        Rowing => "rowing",
        RssFeed => "rss_feed",
        RvHookup => "rv_hookup",
        Satellite => "satellite",
        Save => "save",
        Scanner => "scanner",
        Schedule => "schedule",
        School => "school",
        ScreenLockLandscape => "screen_lock_landscape",
        ScreenLockPortrait => "screen_lock_portrait",
        ScreenLockRotation => "screen_lock_rotation",
        ScreenRotation => "screen_rotation",
        ScreenShare => "screen_share",
        SdCard => "sd_card",
        SdStorage => "sd_storage",
        Search => "search",
        Security => "security",
        SelectAll => "select_all",
        Send => "send",
        SentimentDissatisfied => "sentiment_dissatisfied",
        SentimentNeutral => "sentiment_neutral",
        SentimentSatisfied => "sentiment_satisfied",
        SentimentVeryDissatisfied => "sentiment_very_dissatisfied",
        SentimentVerySatisfied => "sentiment_very_satisfied",
        Settings => "settings",
        SettingsApplications => "settings_applications",
        SettingsBackupRestore => "settings_backup_restore",
        SettingsBluetooth => "settings_bluetooth",
        SettingsBrightness => "settings_brightness",
        SettingsCell => "settings_cell",
        SettingsEthernet => "settings_ethernet",
        SettingsInputAntenna => "settings_input_antenna",
        SettingsInputComponent => "settings_input_component",
        SettingsInputComposite => "settings_input_composite",
        SettingsInputHdmi => "settings_input_hdmi",
        SettingsInputSvideo => "settings_input_svideo",
        SettingsOverscan => "settings_overscan",
        SettingsPhone => "settings_phone",
        SettingsPower => "settings_power",
        SettingsRemote => "settings_remote",
        SettingsSystemDaydream => "settings_system_daydream",
        SettingsVoice => "settings_voice",
        Share => "share",
        Shop => "shop",
        ShopTwo => "shop_two",
        ShoppingBasket => "shopping_basket",
        ShoppingCart => "shopping_cart",
        ShortText => "short_text",
        ShowChart => "show_chart",
        Shuffle => "shuffle",
        SignalCellular4Bar => "signal_cellular_4_bar",
        SignalCellularConnectedNoInternet4Bar => "signal_cellular_connected_no_internet_4_bar",
        SignalCellularNoSim => "signal_cellular_no_sim",
        SignalCellularNull => "signal_cellular_null",
        SignalCellularOff => "signal_cellular_off",
        SignalWifi4Bar => "signal_wifi_4_bar",
        SignalWifi4BarLock => "signal_wifi_4_bar_lock",
        SignalWifiOff => "signal_wifi_off",
        SimCard => "sim_card",
        SimCardAlert => "sim_card_alert",
        SkipNext => "skip_next",
        SkipPrevious => "skip_previous",
        Slideshow => "slideshow",
        SlowMotionVideo => "slow_motion_video",
        Smartphone => "smartphone",
        SmokeFree => "smoke_free",
        SmokingRooms => "smoking_rooms",
        Sms => "sms",
        SmsFailed => "sms_failed",
        Snooze => "snooze",
        Sort => "sort",
        SortByAlpha => "sort_by_alpha",
        Spa => "spa",
        SpaceBar => "space_bar",
        Speaker => "speaker",
        SpeakerGroup => "speaker_group",
        SpeakerNotes => "speaker_notes",
        SpeakerNotesOff => "speaker_notes_off",
        SpeakerPhone => "speaker_phone",
        Spellcheck => "spellcheck",
        Star => "star",
        StarBorder => "star_border",
        StarHalf => "star_half",
        Stars => "stars",
        StayCurrentLandscape => "stay_current_landscape",
        StayCurrentPortrait => "stay_current_portrait",
        StayPrimaryLandscape => "stay_primary_landscape",
        StayPrimaryPortrait => "stay_primary_portrait",
        Stop => "stop",
        StopScreenShare => "stop_screen_share",
        Storage => "storage",
        Store => "store",
        StoreMallDirectory => "store_mall_directory",
        Straighten => "straighten",
        Streetview => "streetview",
        StrikethroughS => "strikethrough_s",
        Style => "style",
        SubdirectoryArrowLeft => "subdirectory_arrow_left",
        SubdirectoryArrowRight => "subdirectory_arrow_right",
        Subject => "subject",
        Subscriptions => "subscriptions",
        Subtitles => "subtitles",
        Subway => "subway",
        SupervisorAccount => "supervisor_account",
        SurroundSound => "surround_sound",
        SwapCalls => "swap_calls",
        SwapHoriz => "swap_horiz",
        SwapVert => "swap_vert",
        SwapVerticalCircle => "swap_vertical_circle",
        SwitchCamera => "switch_camera",
        SwitchVideo => "switch_video",
        Sync => "sync",
        SyncDisabled => "sync_disabled",
        SyncProblem => "sync_problem",
        SystemUpdate => "system_update",
        SystemUpdateAlt => "system_update_alt",
        Tab => "tab",
        TabUnselected => "tab_unselected",
        Tablet => "tablet",
        TabletAndroid => "tablet_android",
        TabletMac => "tablet_mac",
        TagFaces => "tag_faces",
        TapAndPlay => "tap_and_play",
        Terrain => "terrain",
        TextFields => "text_fields",
        TextFormat => "text_format",
        Textsms => "textsms",
        Texture => "texture",
        Theaters => "theaters",
        ThumbDown => "thumb_down",
        ThumbUp => "thumb_up",
        ThumbsUpDown => "thumbs_up_down",
        TimeToLeave => "time_to_leave",
        Timelapse => "timelapse",
        Timeline => "timeline",
        Timer => "timer",
        Timer10 => "timer_10",
        Timer3 => "timer_3",
        TimerOff => "timer_off",
        Title => "title",
        Toc => "toc",
        Today => "today",
        Toll => "toll",
        Tonality => "tonality",
        TouchApp => "touch_app",
        Toys => "toys",
        TrackChanges => "track_changes",
        Traffic => "traffic",
        Train => "train",
        Tram => "tram",
        TransferWithinAStation => "transfer_within_a_station",
        Transform => "transform",
        Translate => "translate",
        TrendingDown => "trending_down",
        TrendingFlat => "trending_flat",
        TrendingUp => "trending_up",
        Tune => "tune",
        TurnedIn => "turned_in",
        TurnedInNot => "turned_in_not",
        Tv => "tv",
        Unarchive => "unarchive",
        Undo => "undo",
        UnfoldLess => "unfold_less",
        UnfoldMore => "unfold_more",
        Update => "update",
        Usb => "usb",
        VerifiedUser => "verified_user",
        VerticalAlignBottom => "vertical_align_bottom",
        VerticalAlignCenter => "vertical_align_center",
        VerticalAlignTop => "vertical_align_top",
        Vibration => "vibration",
        VideoCall => "video_call",
        VideoLabel => "video_label",
        VideoLibrary => "video_library",
        Videocam => "videocam",
        VideocamOff => "videocam_off",
        VideogameAsset => "videogame_asset",
        ViewAgenda => "view_agenda",
        ViewArray => "view_array",
        ViewCarousel => "view_carousel",
        ViewColumn => "view_column",
        ViewComfy => "view_comfy",
        ViewCompact => "view_compact",
        ViewDay => "view_day",
        ViewHeadline => "view_headline",
        ViewList => "view_list",
        ViewModule => "view_module",
        ViewQuilt => "view_quilt",
        ViewStream => "view_stream",
        ViewWeek => "view_week",
        Vignette => "vignette",
        Visibility => "visibility",
        VisibilityOff => "visibility_off",
        VoiceChat => "voice_chat",
        Voicemail => "voicemail",
        VolumeDown => "volume_down",
        VolumeMute => "volume_mute",
        VolumeOff => "volume_off",
        VolumeUp => "volume_up",
        VpnKey => "vpn_key",
        VpnLock => "vpn_lock",
        Wallpaper => "wallpaper",
        Warning => "warning",
        Watch => "watch",
        WatchLater => "watch_later",
        WbAuto => "wb_auto",
        WbCloudy => "wb_cloudy",
        WbIncandescent => "wb_incandescent",
        WbIridescent => "wb_iridescent",
        WbSunny => "wb_sunny",
        Wc => "wc",
        Web => "web",
        WebAsset => "web_asset",
        Weekend => "weekend",
        Whatshot => "whatshot",
        Widgets => "widgets",
        Wifi => "wifi",
        WifiLock => "wifi_lock",
        WifiTethering => "wifi_tethering",
        Work => "work",
        WrapText => "wrap_text",
        YoutubeSearchedFor => "youtube_searched_for",
        ZoomIn => "zoom_in",
        ZoomOut => "zoom_out",
        ZoomOutMap => "zoom_out_map",
    }
}
